// sgStyleSnap2025-BASE44/sgStyleSnap2025-BASE44/src/pages/Cabinet.vue
<template>
  <div class="min-h-screen p-6 md:p-12">
    <!-- Header -->
    <div class="max-w-6xl mx-auto mb-8">
      <div class="flex items-center justify-between mb-6">
        <h1 :class="`text-4xl font-bold ${
          theme.value === 'dark' ? 'text-white' : 'text-black'
        }`">
          Your Cabinet
        </h1>
        <button
          @click="showUpload = true"
          :class="`flex items-center gap-2 px-6 py-3 rounded-xl font-medium transition-all duration-200 hover:scale-105 ${
            theme.value === 'dark'
              ? 'bg-white text-black hover:bg-zinc-200'
              : 'bg-black text-white hover:bg-zinc-800'
          }`"
        >
          <Plus class="w-5 h-5" />
          Add Item
        </button>
      </div>

      <!-- Filters -->
      <div class="flex flex-wrap gap-4 mb-6">
        <button
          v-for="category in categories"
          :key="category"
          @click="activeCategory = category"
          :class="`px-4 py-2 rounded-lg font-medium transition-all duration-200 ${
            activeCategory === category
              ? theme.value === 'dark'
                ? 'bg-white text-black'
                : 'bg-black text-white'
              : theme.value === 'dark'
              ? 'bg-zinc-800 text-zinc-300 hover:bg-zinc-700'
              : 'bg-stone-100 text-stone-700 hover:bg-stone-200'
          }`"
        >
          {{ category === 'all' ? 'All Items' : category }}
        </button>
        
        <button
          @click="showFavoritesOnly = !showFavoritesOnly"
          :class="`flex items-center gap-2 px-4 py-2 rounded-lg font-medium transition-all duration-200 ${
            showFavoritesOnly
              ? theme.value === 'dark'
                ? 'bg-red-600 text-white'
                : 'bg-red-500 text-white'
              : theme.value === 'dark'
              ? 'bg-zinc-800 text-zinc-300 hover:bg-zinc-700'
              : 'bg-stone-100 text-stone-700 hover:bg-stone-200'
          }`"
        >
          <Heart :class="`w-4 h-4 ${showFavoritesOnly ? 'fill-current' : ''}`" />
          Favorites
        </button>
      </div>
    </div>

    <!-- Items Grid -->
    <div class="max-w-6xl mx-auto">
      <div v-if="loading" class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
        <div
          v-for="i in 8"
          :key="i"
          :class="`aspect-square rounded-xl animate-pulse ${
            theme.value === 'dark' ? 'bg-zinc-800' : 'bg-stone-200'
          }`"
        />
      </div>

      <div v-else-if="filteredItems.length === 0" class="text-center py-12">
        <div :class="`w-24 h-24 mx-auto mb-4 rounded-full flex items-center justify-center ${
          theme.value === 'dark' ? 'bg-zinc-800' : 'bg-stone-100'
        }`">
          <Shirt :class="`w-12 h-12 ${theme.value === 'dark' ? 'text-zinc-400' : 'text-stone-500'}`" />
        </div>
        <h3 :class="`text-xl font-semibold mb-2 ${
          theme.value === 'dark' ? 'text-white' : 'text-black'
        }`">
          No items found
        </h3>
        <p :class="`text-lg ${
          theme.value === 'dark' ? 'text-zinc-400' : 'text-stone-600'
        }`">
          Start building your wardrobe by adding your first item!
        </p>
      </div>

      <div v-else class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
        <div
          v-for="item in filteredItems"
          :key="item.id"
          :class="`group cursor-pointer transition-all duration-300 hover:scale-105 ${
            theme.value === 'dark'
              ? 'bg-zinc-900 border border-zinc-800 hover:border-zinc-700'
              : 'bg-white border border-stone-200 hover:border-stone-300'
          } rounded-xl overflow-hidden`"
        >
          <div class="aspect-square relative overflow-hidden">
            <img
              v-if="item.image_url"
              :src="item.image_url"
              :alt="item.name"
              class="w-full h-full object-cover group-hover:scale-110 transition-transform duration-300"
            />
            <div
              v-else
              :class="`w-full h-full flex items-center justify-center ${
                theme.value === 'dark' ? 'bg-zinc-800' : 'bg-stone-100'
              }`"
            >
              <Shirt :class="`w-12 h-12 ${theme.value === 'dark' ? 'text-zinc-400' : 'text-stone-500'}`" />
            </div>
            
            <button
              @click="toggleFavorite(item)"
              :class="`absolute top-2 right-2 p-2 rounded-full transition-all duration-200 ${
                item.is_favorite
                  ? 'bg-red-500 text-white'
                  : theme.value === 'dark'
                  ? 'bg-zinc-800/80 text-zinc-400 hover:bg-zinc-700/80'
                  : 'bg-white/80 text-stone-500 hover:bg-stone-100/80'
              }`"
            >
              <Heart :class="`w-4 h-4 ${item.is_favorite ? 'fill-current' : ''}`" />
            </button>
          </div>
          
          <div class="p-4">
            <h3 :class="`font-semibold mb-1 ${
              theme.value === 'dark' ? 'text-white' : 'text-black'
            }`">
              {{ item.name }}
            </h3>
            <p :class="`text-sm ${
              theme.value === 'dark' ? 'text-zinc-400' : 'text-stone-600'
            }`">
              {{ item.brand || 'No brand' }}
            </p>
            <span :class="`inline-block px-2 py-1 mt-2 text-xs rounded-full ${
              theme.value === 'dark' ? 'bg-zinc-800 text-zinc-300' : 'bg-stone-100 text-stone-700'
            }`">
              {{ item.category }}
            </span>
          </div>
        </div>
      </div>
    </div>

    <!-- Upload Modal -->
    <div
      v-if="showUpload"
      class="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4"
      @click="showUpload = false"
    >
      <div
        :class="`w-full max-w-md rounded-xl p-6 ${
          theme.value === 'dark' ? 'bg-zinc-900' : 'bg-white'
        }`"
        @click.stop
      >
        <h2 :class="`text-xl font-bold mb-4 ${
          theme.value === 'dark' ? 'text-white' : 'text-black'
        }`">
          Add New Item
        </h2>
        
        <form @submit.prevent="handleUpload">
          <div class="space-y-4">
            <div>
              <label :class="`block text-sm font-medium mb-2 ${
                theme.value === 'dark' ? 'text-zinc-300' : 'text-stone-700'
              }`">
                Item Name
              </label>
              <input
                v-model="newItem.name"
                type="text"
                required
                :class="`w-full px-3 py-2 rounded-lg border ${
                  theme.value === 'dark'
                    ? 'bg-zinc-800 border-zinc-700 text-white placeholder-zinc-400'
                    : 'bg-white border-stone-300 text-black placeholder-stone-500'
                }`"
                placeholder="Enter item name"
              />
            </div>
            
            <div>
              <label :class="`block text-sm font-medium mb-2 ${
                theme.value === 'dark' ? 'text-zinc-300' : 'text-stone-700'
              }`">
                Category
              </label>
              <select
                v-model="newItem.category"
                required
                :class="`w-full px-3 py-2 rounded-lg border ${
                  theme.value === 'dark'
                    ? 'bg-zinc-800 border-zinc-700 text-white placeholder-zinc-400'
                    : 'bg-white border-stone-300 text-black placeholder-stone-500'
                }`"
              >
                <option value="">Select category</option>
                <option value="tops">Tops</option>
                <option value="bottoms">Bottoms</option>
                <option value="outerwear">Outerwear</option>
                <option value="shoes">Shoes</option>
                <option value="accessories">Accessories</option>
              </select>
            </div>
            
            <div>
              <label :class="`block text-sm font-medium mb-2 ${
                theme.value === 'dark' ? 'text-zinc-300' : 'text-stone-700'
              }`">
                Brand
              </label>
              <input
                v-model="newItem.brand"
                type="text"
                :class="`w-full px-3 py-2 rounded-lg border ${
                  theme.value === 'dark'
                    ? 'bg-zinc-800 border-zinc-700 text-white placeholder-zinc-400'
                    : 'bg-white border-stone-300 text-black placeholder-stone-500'
                }`"
                placeholder="Enter brand (optional)"
              />
            </div>
            
            <div>
              <label :class="`block text-sm font-medium mb-2 ${
                theme.value === 'dark' ? 'text-zinc-300' : 'text-stone-700'
              }`">
                Image
              </label>
              <input
                ref="fileInput"
                type="file"
                accept="image/*"
                @change="handleFileSelect"
                :class="`w-full px-3 py-2 rounded-lg border ${
                  theme.value === 'dark'
                    ? 'bg-zinc-800 border-zinc-700 text-white placeholder-zinc-400'
                    : 'bg-white border-stone-300 text-black placeholder-stone-500'
                }`"
              />
            </div>
          </div>
          
          <div class="flex gap-3 mt-6">
            <button
              type="button"
              @click="showUpload = false"
              :class="`flex-1 px-4 py-2 rounded-lg font-medium transition-all duration-200 ${
                theme.value === 'dark'
                  ? 'bg-zinc-800 text-zinc-300 hover:bg-zinc-700'
                  : 'bg-stone-100 text-stone-700 hover:bg-stone-200'
              }`"
            >
              Cancel
            </button>
            <button
              type="submit"
              :disabled="uploading"
              :class="`flex-1 px-4 py-2 rounded-lg font-medium transition-all duration-200 ${
                theme.value === 'dark'
                  ? 'bg-white text-black hover:bg-zinc-200'
                  : 'bg-black text-white hover:bg-zinc-800'
              } ${uploading ? 'opacity-50 cursor-not-allowed' : ''}`"
            >
              {{ uploading ? 'Adding...' : 'Add Item' }}
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useTheme } from '@/composables/useTheme'
import { useAuthStore } from '@/stores/auth-store'
import { api } from '@/api/base44Client'
import { Plus, Heart, Shirt } from 'lucide-vue-next'

const { theme } = useTheme()
const authStore = useAuthStore()

// User state for base44Client
const currentUser = ref(null)

const items = ref([])
const loading = ref(true)
const showUpload = ref(false)
const activeCategory = ref('all')
const showFavoritesOnly = ref(false)
const uploading = ref(false)
const fileInput = ref(null)

const newItem = ref({
  name: '',
  category: '',
  brand: '',
  image_url: ''
})

const categories = ['all', 'tops', 'bottoms', 'outerwear', 'shoes', 'accessories']

const filteredItems = computed(() => {
  let filtered = items.value

  if (activeCategory.value !== 'all') {
    filtered = filtered.filter(item => item.category === activeCategory.value)
  }

  if (showFavoritesOnly.value) {
    filtered = filtered.filter(item => item.is_favorite)
  }

  return filtered
})

const loadItems = async () => {
  try {
    if (currentUser.value?.email) {
      console.log('Cabinet: Loading items for user:', currentUser.value.email)
      const itemsData = await api.entities.ClothingItem.filter(
        { created_by: currentUser.value.email },
        '-created_date'
      )
      console.log('Cabinet: Loaded items:', itemsData)
      items.value = itemsData
    } else {
      console.log('Cabinet: No current user email found')
    }
  } catch (error) {
    console.error('Error loading items:', error)
  } finally {
    loading.value = false
  }
}

const toggleFavorite = async (item) => {
  try {
    await api.entities.ClothingItem.toggleFavorite(item.id)
    item.is_favorite = !item.is_favorite
  } catch (error) {
    console.error('Error toggling favorite:', error)
  }
}

const handleFileSelect = (event) => {
  const file = event.target.files[0]
  if (file) {
    const reader = new FileReader()
    reader.onload = (e) => {
      newItem.value.image_url = e.target.result
    }
    reader.readAsDataURL(file)
  }
}

const handleUpload = async () => {
  if (!newItem.value.name || !newItem.value.category) return

  uploading.value = true
  try {
    const itemData = {
      ...newItem.value,
      created_by: currentUser.value.email
    }
    
    const newItemData = await api.entities.ClothingItem.create(itemData)
    items.value.unshift(newItemData)
    
    // Reset form
    newItem.value = {
      name: '',
      category: '',
      brand: '',
      image_url: ''
    }
    
    // Reset file input
    if (fileInput.value) {
      fileInput.value.value = ''
    }
    
    showUpload.value = false
  } catch (error) {
    console.error('Error uploading item:', error)
  } finally {
    uploading.value = false
  }
}

onMounted(async () => {
  try {
    // Load user using base44Client
    const userData = await api.auth.me()
    currentUser.value = userData
    console.log('Cabinet: Loaded user:', userData)
    
    await loadItems()
  } catch (error) {
    console.error('Error loading user:', error)
  }
})
</script>

// src/pages/cabinet.jsx
import React, { useState, useEffect } from "react";
import { api } from "@/api/client";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useTheme } from "../components/ThemeContext";
import { motion, AnimatePresence } from "framer-motion";
import { Plus, Heart, Filter } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";
import { createPageUrl } from "@/utils";

import UploadItemModal from "../components/cabinet/uploaditemodal";
import ClothingItemCard from "../components/cabinet/ClothingItemCard";
import CategoryFilter from "../components/cabinet/CategoryFilter";

export default function Cabinet() {
  const { theme } = useTheme();
  const queryClient = useQueryClient();
  const [showUpload, setShowUpload] = useState(false);
  const [activeCategory, setActiveCategory] = useState("all");
  const [showFavoritesOnly, setShowFavoritesOnly] = useState(false);
  const [currentUser, setCurrentUser] = useState(null);
  const [activeTab, setActiveTab] = useState("items");

  useEffect(() => {
    const loadUser = async () => {
      try {
        const userData = await api.auth.me();
        setCurrentUser(userData);
      } catch (error) {
        console.error("Error loading user:", error);
      }
    };
    loadUser();
  }, []);

  const { data: items = [], isLoading } = useQuery({
    queryKey: ["clothing-items", currentUser?.email],
    queryFn: () => {
      if (!currentUser?.email) return [];
      return api.entities.ClothingItem.filter(
        { created_by: currentUser.email },
        "-created_date"
      );
    },
    enabled: !!currentUser?.email,
  });

  const { data: outfits = [], isLoading: outfitsLoading } = useQuery({
    queryKey: ["outfits", currentUser?.email],
    queryFn: () => {
      if (!currentUser?.email) return [];
      return api.entities.Outfit.filter(
        { created_by: currentUser.email },
        "-created_date"
      );
    },
    enabled: !!currentUser?.email,
  });

  const deleteMutation = useMutation({
    mutationFn: (id) => api.entities.ClothingItem.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["clothing-items"] });
    },
  });

  const deleteOutfitMutation = useMutation({
    mutationFn: (id) => api.entities.Outfit.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["outfits"] });
    },
  });

  const toggleFavoriteMutation = useMutation({
    mutationFn: ({ id, is_favorite }) =>
      api.entities.ClothingItem.update(id, { is_favorite: !is_favorite }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["clothing-items"] });
    },
  });

  const toggleOutfitFavoriteMutation = useMutation({
    mutationFn: ({ id, is_favorite }) =>
      api.entities.Outfit.update(id, { is_favorite: !is_favorite }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["outfits"] });
    },
  });

  const filteredItems = items.filter((item) => {
    const categoryMatch = activeCategory === "all" || item.category === activeCategory;
    const favoriteMatch = !showFavoritesOnly || item.is_favorite;
    return categoryMatch && favoriteMatch;
  });

  const filteredOutfits = showFavoritesOnly 
    ? outfits.filter(outfit => outfit.is_favorite)
    : outfits;

  return (
    <div className="min-h-screen p-6 md:p-12">
      {/* Header */}
      <div className="max-w-7xl mx-auto mb-12">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6 mb-8">
          <div>
            <h1 className={`text-4xl md:text-5xl font-bold tracking-tight mb-2 ${
              theme === "dark" ? "text-white" : "text-black"
            }`}>
              My Cabinet
            </h1>
            <p className={`text-lg ${
              theme === "dark" ? "text-zinc-400" : "text-stone-600"
            }`}>
              {activeTab === "items" 
                ? `${filteredItems.length} ${filteredItems.length === 1 ? "item" : "items"}`
                : `${filteredOutfits.length} ${filteredOutfits.length === 1 ? "outfit" : "outfits"}`
              }
            </p>
          </div>

          <div className="flex flex-wrap gap-3">
            <Button
              onClick={() => setShowFavoritesOnly(!showFavoritesOnly)}
              variant={showFavoritesOnly ? "default" : "outline"}
              className={`gap-2 ${
                showFavoritesOnly
                  ? theme === "dark"
                    ? "bg-white text-black hover:bg-zinc-100"
                    : "bg-black text-white hover:bg-stone-900"
                  : theme === "dark"
                  ? "border-zinc-700 text-zinc-300 hover:bg-zinc-900 hover:text-white"
                  : ""
              }`}
            >
              <Heart className={`w-4 h-4 ${showFavoritesOnly ? "fill-red-500 text-red-500" : ""}`} />
              Favorites
            </Button>

            {activeTab === "items" && (
              <Button
                onClick={() => setShowUpload(true)}
                className={`gap-2 ${
                  theme === "dark"
                    ? "bg-white text-black hover:bg-zinc-100"
                    : "bg-black text-white hover:bg-stone-900"
                }`}
              >
                <Plus className="w-5 h-5" />
                Upload Item
              </Button>
            )}
          </div>
        </div>

        {/* Tab Navigation */}
        <div className="flex gap-2 mb-8">
          <Button
            onClick={() => setActiveTab("items")}
            variant={activeTab === "items" ? "default" : "outline"}
            className={`rounded-full ${
              activeTab === "items"
                ? theme === "dark"
                  ? "bg-white text-black"
                  : "bg-black text-white"
                : theme === "dark"
                ? "border-zinc-700 text-zinc-400"
                : "border-stone-300 text-stone-600"
            }`}
          >
            My Items
          </Button>
          <Button
            onClick={() => setActiveTab("outfits")}
            variant={activeTab === "outfits" ? "default" : "outline"}
            className={`rounded-full ${
              activeTab === "outfits"
                ? theme === "dark"
                  ? "bg-white text-black"
                  : "bg-black text-white"
                : theme === "dark"
                ? "border-zinc-700 text-zinc-400"
                : "border-stone-300 text-stone-600"
            }`}
          >
            Saved Outfits
          </Button>
        </div>

        {/* Category Filter (only for items) */}
        {activeTab === "items" && (
          <CategoryFilter
            activeCategory={activeCategory}
            setActiveCategory={setActiveCategory}
          />
        )}
      </div>

      {/* Content Grid */}
      <div className="max-w-7xl mx-auto">
        {activeTab === "items" ? (
          // Items Grid
          isLoading ? (
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-6">
              {Array(10).fill(0).map((_, i) => (
                <div
                  key={i}
                  className={`aspect-square rounded-3xl ${
                    theme === "dark" ? "bg-zinc-900" : "bg-stone-200"
                  } animate-pulse`}
                />
              ))}
            </div>
          ) : filteredItems.length === 0 ? (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className={`text-center py-24 rounded-3xl ${
                theme === "dark"
                  ? "bg-zinc-900 border border-zinc-800"
                  : "bg-white border border-stone-200"
              }`}
            >
              <div className={`w-24 h-24 mx-auto mb-6 rounded-full ${
                theme === "dark" ? "bg-zinc-800" : "bg-stone-100"
              } flex items-center justify-center`}>
                <Filter className={`w-12 h-12 ${
                  theme === "dark" ? "text-zinc-600" : "text-stone-400"
                }`} />
              </div>
              <h3 className={`text-2xl font-bold mb-2 ${
                theme === "dark" ? "text-white" : "text-black"
              }`}>
                No items found
              </h3>
              <p className={`text-lg mb-6 ${
                theme === "dark" ? "text-zinc-400" : "text-stone-600"
              }`}>
                {showFavoritesOnly
                  ? "You haven't favorited any items yet"
                  : "Start building your wardrobe"}
              </p>
              {!showFavoritesOnly && (
                <Button
                  onClick={() => setShowUpload(true)}
                  className={`gap-2 ${
                    theme === "dark"
                      ? "bg-white text-black hover:bg-zinc-100"
                      : "bg-black text-white hover:bg-stone-900"
                  }`}
                >
                  <Plus className="w-5 h-5" />
                  Upload Your First Item
                </Button>
              )}
            </motion.div>
          ) : (
            <motion.div
              layout
              className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-6"
            >
              <AnimatePresence>
                {filteredItems.map((item) => (
                  <ClothingItemCard
                    key={item.id}
                    item={item}
                    onDelete={() => deleteMutation.mutate(item.id)}
                    onToggleFavorite={() =>
                      toggleFavoriteMutation.mutate({
                        id: item.id,
                        is_favorite: item.is_favorite,
                      })
                    }
                  />
                ))}
              </AnimatePresence>
            </motion.div>
          )
        ) : (
          // Outfits Grid
          outfitsLoading ? (
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
              {Array(6).fill(0).map((_, i) => (
                <div
                  key={i}
                  className={`aspect-[4/3] rounded-3xl ${
                    theme === "dark" ? "bg-zinc-900" : "bg-stone-200"
                  } animate-pulse`}
                />
              ))}
            </div>
          ) : filteredOutfits.length === 0 ? (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className={`text-center py-24 rounded-3xl ${
                theme === "dark"
                  ? "bg-zinc-900 border border-zinc-800"
                  : "bg-white border border-stone-200"
              }`}
            >
              <div className={`w-24 h-24 mx-auto mb-6 rounded-full ${
                theme === "dark" ? "bg-zinc-800" : "bg-stone-100"
              } flex items-center justify-center text-4xl`}>
                👔
              </div>
              <h3 className={`text-2xl font-bold mb-2 ${
                theme === "dark" ? "text-white" : "text-black"
              }`}>
                No outfits saved yet
              </h3>
              <p className={`text-lg mb-6 ${
                theme === "dark" ? "text-zinc-400" : "text-stone-600"
              }`}>
                {showFavoritesOnly
                  ? "You haven't favorited any outfits yet"
                  : "Create your first outfit in the Studio"}
              </p>
              {!showFavoritesOnly && (
                <Link to={createPageUrl("Dashboard")}>
                  <Button
                    className={`gap-2 ${
                      theme === "dark"
                        ? "bg-white text-black hover:bg-zinc-100"
                        : "bg-black text-white hover:bg-stone-900"
                    }`}
                  >
                    Go to Outfit Studio
                  </Button>
                </Link>
              )}
            </motion.div>
          ) : (
            <motion.div
              layout
              className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6"
            >
              <AnimatePresence>
                {filteredOutfits.map((outfit) => (
                  <motion.div
                    key={outfit.id}
                    layout
                    initial={{ opacity: 0, scale: 0.9 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.9 }}
                    whileHover={{ y: -8 }}
                    className={`group relative aspect-[4/3] rounded-3xl overflow-hidden ${
                      theme === "dark"
                        ? "bg-zinc-900 border border-zinc-800"
                        : "bg-white border border-stone-200"
                    } transition-all duration-300 cursor-pointer`}
                  >
                    <Link to={`${createPageUrl("Dashboard")}?outfit=${outfit.id}`}>
                      <div className="w-full h-full p-4 flex items-center justify-center">
                        <div className="text-center">
                          <div className="text-6xl mb-4">👔</div>
                          <h3 className={`font-semibold text-lg ${
                            theme === "dark" ? "text-white" : "text-black"
                          }`}>
                            {outfit.name}
                          </h3>
                        </div>
                      </div>
                    </Link>

                    {/* Favorite Badge */}
                    {outfit.is_favorite && (
                      <div className="absolute top-3 right-3">
                        <div className="p-2 rounded-xl bg-red-500">
                          <Heart className="w-4 h-4 fill-white text-white" />
                        </div>
                      </div>
                    )}

                    {/* Hover Controls */}
                    <div className={`absolute inset-0 ${
                      theme === "dark" ? "bg-black" : "bg-white"
                    } bg-opacity-0 group-hover:bg-opacity-90 transition-all duration-300 flex items-end p-4`}>
                      <div className="opacity-0 group-hover:opacity-100 transition-opacity duration-300 w-full flex gap-2">
                        <Button
                          onClick={(e) => {
                            e.preventDefault();
                            e.stopPropagation();
                            toggleOutfitFavoriteMutation.mutate({
                              id: outfit.id,
                              is_favorite: outfit.is_favorite,
                            });
                          }}
                          variant="outline"
                          size="icon"
                          className={`rounded-xl flex-1 ${
                            outfit.is_favorite
                              ? "bg-red-500 border-red-500 text-white hover:bg-red-600"
                              : theme === "dark"
                              ? "border-zinc-700 text-zinc-300 hover:bg-zinc-800"
                              : "border-stone-300 text-stone-700 hover:bg-stone-100"
                          }`}
                        >
                          <Heart className={`w-4 h-4 ${outfit.is_favorite ? "fill-current" : ""}`} />
                        </Button>
                        
                        <Button
                          onClick={(e) => {
                            e.preventDefault();
                            e.stopPropagation();
                            deleteOutfitMutation.mutate(outfit.id);
                          }}
                          variant="outline"
                          size="icon"
                          className={`rounded-xl hover:bg-red-500 hover:text-white hover:border-red-500 ${
                            theme === "dark" 
                              ? "border-zinc-700 text-zinc-300" 
                              : "border-stone-300 text-stone-700"
                          }`}
                        >
                          <Filter className="w-4 h-4" />
                        </Button>
                      </div>
                    </div>
                  </motion.div>
                ))}
              </AnimatePresence>
            </motion.div>
          )
        )}
      </div>

      {/* Upload Modal */}
      <UploadItemModal
        open={showUpload}
        onClose={() => setShowUpload(false)}
      />
    </div>
  );
}
