// src/pages/FriendCabinet.vue
<template>
  <div class="min-h-screen p-6 md:p-12">
    <div class="max-w-6xl mx-auto">
      <!-- Header -->
      <div class="flex items-center justify-between mb-8">
        <div class="flex items-center gap-4">
          <button
            @click="$router.back()"
            :class="`p-2 rounded-lg transition-all duration-200 ${
              theme.value === 'dark'
                ? 'bg-zinc-800 text-zinc-300 hover:bg-zinc-700'
                : 'bg-stone-100 text-stone-700 hover:bg-stone-200'
            }`"
          >
            <ArrowLeft class="w-5 h-5" />
          </button>
          <div>
            <h1 :class="`text-4xl font-bold ${
              theme.value === 'dark' ? 'text-white' : 'text-black'
            }`">
              {{ friend?.name || 'Friend' }}'s Closet
            </h1>
            <p :class="`text-lg ${
              theme.value === 'dark' ? 'text-zinc-400' : 'text-stone-600'
            }`">
              Browse their wardrobe and get style inspiration
            </p>
          </div>
        </div>
        
        <div class="flex items-center gap-3">
          <button
            @click="toggleView"
            :class="`p-2 rounded-lg transition-all duration-200 ${
              theme.value === 'dark'
                ? 'bg-zinc-800 text-zinc-300 hover:bg-zinc-700'
                : 'bg-stone-100 text-stone-700 hover:bg-stone-200'
            }`"
          >
            <component :is="viewMode === 'grid' ? List : Grid" class="w-5 h-5" />
          </button>
        </div>
      </div>

      <!-- Friend Info -->
      <div v-if="friend" :class="`rounded-xl p-6 mb-8 ${
        theme.value === 'dark' ? 'bg-zinc-900 border border-zinc-800' : 'bg-white border border-stone-200'
      }`">
        <div class="flex items-center gap-6">
          <div :class="`w-20 h-20 rounded-full overflow-hidden ${
            theme.value === 'dark' ? 'bg-zinc-800' : 'bg-stone-100'
          }`">
            <img
              v-if="friend.avatar_url"
              :src="friend.avatar_url"
              :alt="friend.name"
              class="w-full h-full object-cover"
            />
            <div
              v-else
              :class="`w-full h-full flex items-center justify-center ${
                theme.value === 'dark' ? 'bg-zinc-700' : 'bg-stone-200'
              }`"
            >
              <User :class="`w-10 h-10 ${theme.value === 'dark' ? 'text-zinc-400' : 'text-stone-500'}`" />
            </div>
          </div>
          <div class="flex-1">
            <h2 :class="`text-2xl font-bold ${
              theme.value === 'dark' ? 'text-white' : 'text-black'
            }`">
              {{ friend.name }}
            </h2>
            <p :class="`text-lg ${
              theme.value === 'dark' ? 'text-zinc-400' : 'text-stone-600'
            }`">
              @{{ friend.username }}
            </p>
            <div class="flex gap-6 mt-2">
              <div class="text-center">
                <p :class="`text-2xl font-bold ${
                  theme.value === 'dark' ? 'text-white' : 'text-black'
                }`">
                  {{ friend.outfit_count || 0 }}
                </p>
                <p :class="`text-sm ${
                  theme.value === 'dark' ? 'text-zinc-400' : 'text-stone-600'
                }`">
                  Outfits
                </p>
              </div>
              <div class="text-center">
                <p :class="`text-2xl font-bold ${
                  theme.value === 'dark' ? 'text-white' : 'text-black'
                }`">
                  {{ friend.item_count || 0 }}
                </p>
                <p :class="`text-sm ${
                  theme.value === 'dark' ? 'text-zinc-400' : 'text-stone-600'
                }`">
                  Items
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Filters -->
      <div :class="`rounded-xl p-6 mb-8 ${
        theme.value === 'dark' ? 'bg-zinc-900 border border-zinc-800' : 'bg-white border border-stone-200'
      }`">
        <div class="flex flex-col md:flex-row gap-4">
          <div class="flex-1">
            <input
              v-model="searchQuery"
              type="text"
              placeholder="Search items..."
              :class="`w-full px-4 py-3 rounded-lg border ${
                theme.value === 'dark'
                  ? 'bg-zinc-800 border-zinc-700 text-white placeholder-zinc-400'
                  : 'bg-white border-stone-300 text-black placeholder-stone-500'
              }`"
            />
          </div>
          <div class="flex gap-2">
            <button
              v-for="category in categories"
              :key="category"
              @click="activeCategory = category"
              :class="`px-4 py-3 rounded-lg font-medium transition-all duration-200 ${
                activeCategory === category
                  ? theme.value === 'dark'
                    ? 'bg-white text-black'
                    : 'bg-black text-white'
                  : theme.value === 'dark'
                  ? 'bg-zinc-800 text-zinc-300 hover:bg-zinc-700'
                  : 'bg-stone-100 text-stone-700 hover:bg-stone-200'
              }`"
            >
              {{ category === 'all' ? 'All' : category }}
            </button>
          </div>
        </div>
      </div>

      <!-- Items Grid/List -->
      <div v-if="loading" class="text-center py-12">
        <div :class="`w-12 h-12 mx-auto mb-4 border-2 border-current border-t-transparent rounded-full animate-spin ${
          theme.value === 'dark' ? 'text-white' : 'text-black'
        }`" />
        <p :class="`text-lg ${
          theme.value === 'dark' ? 'text-zinc-400' : 'text-stone-600'
        }`">
          Loading items...
        </p>
      </div>

      <div v-else-if="filteredItems.length === 0" class="text-center py-12">
        <div :class="`w-24 h-24 mx-auto mb-4 rounded-full flex items-center justify-center ${
          theme.value === 'dark' ? 'bg-zinc-800' : 'bg-stone-100'
        }`">
          <Shirt :class="`w-12 h-12 ${theme.value === 'dark' ? 'text-zinc-400' : 'text-stone-500'}`" />
        </div>
        <h2 :class="`text-2xl font-semibold mb-2 ${
          theme.value === 'dark' ? 'text-white' : 'text-black'
        }`">
          No items found
        </h2>
        <p :class="`text-lg ${
          theme.value === 'dark' ? 'text-zinc-400' : 'text-stone-600'
        }`">
          {{ searchQuery ? 'Try adjusting your search' : 'This friend hasn\'t added any items yet' }}
        </p>
      </div>

      <div v-else :class="viewMode === 'grid' ? 'grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6' : 'space-y-4'">
        <div
          v-for="item in filteredItems"
          :key="item.id"
          :class="`group relative transition-all duration-300 cursor-pointer hover:-translate-y-2 ${
            viewMode === 'grid'
              ? 'aspect-square rounded-3xl overflow-hidden'
              : 'flex items-center gap-4 p-4 rounded-xl'
          } ${
            theme.value === 'dark'
              ? 'bg-zinc-900 border border-zinc-800 hover:border-zinc-700'
              : 'bg-white border border-stone-200 hover:border-stone-300'
          }`"
        >
          <!-- Image -->
          <div :class="viewMode === 'grid' ? 'w-full h-full p-4 flex items-center justify-center' : 'w-20 h-20 rounded-lg overflow-hidden flex-shrink-0'">
            <img
              v-if="item.image_url"
              :src="item.image_url"
              :alt="item.name"
              :class="viewMode === 'grid' ? 'max-w-full max-h-full object-contain' : 'w-full h-full object-cover'"
            />
            <div
              v-else
              :class="`w-full h-full flex items-center justify-center ${
                theme.value === 'dark' ? 'bg-zinc-800' : 'bg-stone-100'
              }`"
            >
              <Shirt :class="`${viewMode === 'grid' ? 'w-12 h-12' : 'w-6 h-6'} ${theme.value === 'dark' ? 'text-zinc-400' : 'text-stone-500'}`" />
            </div>
          </div>

          <!-- Overlay (Grid view only) -->
          <div v-if="viewMode === 'grid'" :class="`absolute inset-0 transition-all duration-300 flex flex-col justify-end p-4 ${
            theme.value === 'dark' ? 'bg-black' : 'bg-white'
          } bg-opacity-0 group-hover:bg-opacity-90`">
            <div class="opacity-0 group-hover:opacity-100 transition-opacity duration-300">
              <h3 :class="`font-semibold text-lg mb-1 ${
                theme.value === 'dark' ? 'text-white' : 'text-black'
              }`">
                {{ item.name }}
              </h3>
              <p :class="`text-sm mb-3 ${
                theme.value === 'dark' ? 'text-zinc-400' : 'text-stone-600'
              }`">
                {{ item.category }}
                {{ item.brand ? ` • ${item.brand}` : '' }}
              </p>
            </div>
          </div>

          <!-- List view content -->
          <div v-if="viewMode === 'list'" class="flex-1">
            <h3 :class="`font-semibold text-lg ${
              theme.value === 'dark' ? 'text-white' : 'text-black'
            }`">
              {{ item.name }}
            </h3>
            <p :class="`text-sm ${
              theme.value === 'dark' ? 'text-zinc-400' : 'text-stone-600'
            }`">
              {{ item.category }}
              {{ item.brand ? ` • ${item.brand}` : '' }}
            </p>
            <p :class="`text-xs mt-1 ${
              theme.value === 'dark' ? 'text-zinc-500' : 'text-stone-500'
            }`">
              Added {{ formatDate(item.created_at) }}
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { useTheme } from '@/composables/useTheme'
import { api } from '@/api/client'
import { formatDate } from '@/utils'
import { ArrowLeft, User, Shirt, Grid, List } from 'lucide-vue-next'

const route = useRoute()
const { theme } = useTheme()
const friend = ref(null)
const items = ref([])
const loading = ref(true)
const searchQuery = ref('')
const activeCategory = ref('all')
const viewMode = ref('grid')

const categories = ['all', 'tops', 'bottoms', 'shoes', 'outerwear', 'accessories']

const filteredItems = computed(() => {
  let filtered = items.value

  if (activeCategory.value !== 'all') {
    filtered = filtered.filter(item => item.category === activeCategory.value)
  }

  if (searchQuery.value) {
    const query = searchQuery.value.toLowerCase()
    filtered = filtered.filter(item => 
      item.name.toLowerCase().includes(query) ||
      item.brand?.toLowerCase().includes(query) ||
      item.category.toLowerCase().includes(query)
    )
  }

  return filtered
})

const loadFriend = async () => {
  try {
    const friendId = route.query.friendId
    if (!friendId) {
      console.error('No friend ID provided')
      return
    }

    const friendData = await api.entities.User.get(friendId)
    friend.value = friendData
  } catch (error) {
    console.error('Error loading friend:', error)
  }
}

const loadFriendItems = async () => {
  try {
    const friendId = route.query.friendId
    if (!friendId) return

    const itemsData = await api.entities.ClothingItem.filter(
      { owner_id: friendId },
      '-created_at'
    )
    items.value = itemsData
  } catch (error) {
    console.error('Error loading friend items:', error)
  } finally {
    loading.value = false
  }
}

const toggleView = () => {
  viewMode.value = viewMode.value === 'grid' ? 'list' : 'grid'
}

onMounted(async () => {
  await loadFriend()
  await loadFriendItems()
})
</script>

// src/pages/FriendCabinet.jsx
import React from "react";
import { api } from "@/api/client";
import { useQuery } from "@tanstack/react-query";
import { useTheme } from "../components/ThemeContext";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowLeft, Filter, Lock } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Link, useLocation } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { useState, useEffect } from "react";

import CategoryFilter from "../components/cabinet/CategoryFilter";

export default function FriendCabinet() {
  const { theme } = useTheme();
  const location = useLocation();
  const [activeCategory, setActiveCategory] = useState("all");
  const [currentUser, setCurrentUser] = useState(null);
  const [isFriend, setIsFriend] = useState(false);
  
  const urlParams = new URLSearchParams(location.search);
  const friendEmail = urlParams.get("email");
  const friendName = urlParams.get("name");

  useEffect(() => {
    const loadUser = async () => {
      try {
        const userData = await api.auth.me();
        setCurrentUser(userData);
      } catch (error) {
        console.error("Error loading user:", error);
      }
    };
    loadUser();
  }, []);

  const { data: friendships = [] } = useQuery({
    queryKey: ["friendships-check", currentUser?.email, friendEmail],
    queryFn: () => {
      if (!currentUser?.email || !friendEmail) return [];
      return api.entities.Friendship.filter(
        { created_by: currentUser.email, friend_email: friendEmail, status: "accepted" },
        "-created_date"
      );
    },
    enabled: !!currentUser?.email && !!friendEmail,
    onSuccess: (data) => {
      setIsFriend(data.length > 0);
    }
  });

  const { data: items = [], isLoading } = useQuery({
    queryKey: ["friend-items", friendEmail],
    queryFn: () => {
      if (!friendEmail) return [];
      return api.entities.ClothingItem.filter(
        { created_by: friendEmail },
        "-created_date"
      );
    },
    enabled: !!friendEmail && isFriend,
  });

  const filteredItems = items.filter((item) => 
    activeCategory === "all" || item.category === activeCategory
  );

  // Show access denied if not friends
  if (currentUser && !isLoading && !isFriend && friendships.length === 0) {
    return (
      <div className="min-h-screen p-6 md:p-12">
        <div className="max-w-7xl mx-auto">
          <div className="flex items-center gap-4 mb-8">
            <Link to={createPageUrl("Friends")}>
              <Button variant="outline" size="icon" className="rounded-xl">
                <ArrowLeft className="w-5 h-5" />
              </Button>
            </Link>
          </div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className={`text-center py-24 rounded-3xl ${
              theme === "dark"
                ? "bg-zinc-900 border border-zinc-800"
                : "bg-white border border-stone-200"
            }`}
          >
            <div className={`w-24 h-24 mx-auto mb-6 rounded-full ${
              theme === "dark" ? "bg-zinc-800" : "bg-stone-100"
            } flex items-center justify-center`}>
              <Lock className={`w-12 h-12 ${
                theme === "dark" ? "text-zinc-600" : "text-stone-400"
              }`} />
            </div>
            <h3 className={`text-2xl font-bold mb-2 ${
              theme === "dark" ? "text-white" : "text-black"
            }`}>
              Private Cabinet
            </h3>
            <p className={`text-lg ${
              theme === "dark" ? "text-zinc-400" : "text-stone-600"
            }`}>
              You need to be friends with {friendName} to view their cabinet
            </p>
          </motion.div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen p-6 md:p-12">
      {/* Header */}
      <div className="max-w-7xl mx-auto mb-12">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6 mb-8">
          <div className="flex items-center gap-4">
            <Link to={createPageUrl("Friends")}>
              <Button
                variant="outline"
                size="icon"
                className="rounded-xl"
              >
                <ArrowLeft className="w-5 h-5" />
              </Button>
            </Link>
            <div>
              <h1 className={`text-4xl md:text-5xl font-bold tracking-tight mb-2 ${
                theme === "dark" ? "text-white" : "text-black"
              }`}>
                {friendName}'s Cabinet
              </h1>
              <p className={`text-lg ${
                theme === "dark" ? "text-zinc-400" : "text-stone-600"
              }`}>
                {filteredItems.length} {filteredItems.length === 1 ? "item" : "items"}
              </p>
            </div>
          </div>
        </div>

        {/* Category Filter */}
        <CategoryFilter
          activeCategory={activeCategory}
          setActiveCategory={setActiveCategory}
        />
      </div>

      {/* Items Grid */}
      <div className="max-w-7xl mx-auto">
        {isLoading ? (
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-6">
            {Array(10).fill(0).map((_, i) => (
              <div
                key={i}
                className={`aspect-square rounded-3xl ${
                  theme === "dark" ? "bg-zinc-900" : "bg-stone-200"
                } animate-pulse`}
              />
            ))}
          </div>
        ) : filteredItems.length === 0 ? (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className={`text-center py-24 rounded-3xl ${
              theme === "dark"
                ? "bg-zinc-900 border border-zinc-800"
                : "bg-white border border-stone-200"
            }`}
          >
            <div className={`w-24 h-24 mx-auto mb-6 rounded-full ${
              theme === "dark" ? "bg-zinc-800" : "bg-stone-100"
            } flex items-center justify-center`}>
              <Filter className={`w-12 h-12 ${
                theme === "dark" ? "text-zinc-600" : "text-stone-400"
              }`} />
            </div>
            <h3 className={`text-2xl font-bold mb-2 ${
              theme === "dark" ? "text-white" : "text-black"
            }`}>
              No items found
            </h3>
            <p className={`text-lg ${
              theme === "dark" ? "text-zinc-400" : "text-stone-600"
            }`}>
              {friendName} hasn't added any items yet
            </p>
          </motion.div>
        ) : (
          <motion.div
            layout
            className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-6"
          >
            <AnimatePresence>
              {filteredItems.map((item) => (
                <motion.div
                  key={item.id}
                  layout
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  exit={{ opacity: 0, scale: 0.9 }}
                  whileHover={{ y: -8 }}
                  className={`group relative aspect-square rounded-3xl overflow-hidden ${
                    theme === "dark"
                      ? "bg-zinc-900 border border-zinc-800"
                      : "bg-white border border-stone-200"
                  } transition-all duration-300 cursor-pointer`}
                >
                  <div className="w-full h-full p-4 flex items-center justify-center">
                    <img
                      src={item.image_url}
                      alt={item.name}
                      className="max-w-full max-h-full object-contain"
                    />
                  </div>
                  
                  <div className={`absolute inset-0 ${
                    theme === "dark" ? "bg-black" : "bg-white"
                  } bg-opacity-0 group-hover:bg-opacity-90 transition-all duration-300 flex flex-col justify-end p-4`}>
                    <div className="opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                      <h3 className={`font-semibold text-lg mb-1 ${
                        theme === "dark" ? "text-white" : "text-black"
                      }`}>
                        {item.name}
                      </h3>
                      <p className={`text-sm ${
                        theme === "dark" ? "text-zinc-400" : "text-stone-600"
                      }`}>
                        {item.category}
                        {item.brand && ` • ${item.brand}`}
                      </p>
                    </div>
                  </div>
                </motion.div>
              ))}
            </AnimatePresence>
          </motion.div>
        )}
      </div>
    </div>
  );
}
