// src/components/cabinet/UploadItemModal.jsx
import React, { useState } from "react";
import { api } from "@/api/client";
import { useTheme } from "../ThemeContext";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";

export default function UploadItemModal({ open, onClose }) {
  const { theme } = useTheme();
  const [formData, setFormData] = useState({
    name: "",
    category: "",
    image_url: "",
  });
  const [uploading, setUploading] = useState(false);

  const categories = [
    "tops",
    "bottoms", 
    "shoes",
    "accessories",
    "outerwear"
  ];

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!formData.name || !formData.category || !formData.image_url) return;

    setUploading(true);
    try {
      await api.entities.ClothingItem.create({
        ...formData,
        created_by: "test@example.com", // This would come from auth context
        is_favorite: false
      });
      
      setFormData({ name: "", category: "", image_url: "" });
      onClose();
    } catch (error) {
      console.error("Error uploading item:", error);
    } finally {
      setUploading(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className={`max-w-md ${
        theme === "dark" ? "bg-zinc-900 border-zinc-800" : "bg-white border-stone-200"
      }`}>
        <DialogHeader>
          <DialogTitle className={`text-2xl font-bold ${
            theme === "dark" ? "text-white" : "text-black"
          }`}>
            Upload New Item
          </DialogTitle>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-4 mt-4">
          <div>
            <Label htmlFor="item-name" className={`text-base mb-2 block ${
              theme === "dark" ? "text-zinc-300" : "text-stone-700"
            }`}>
              Item Name
            </Label>
            <Input
              id="item-name"
              value={formData.name}
              onChange={(e) => setFormData({ ...formData, name: e.target.value })}
              placeholder="e.g., Blue Jeans"
              className={`h-12 rounded-xl ${
                theme === "dark"
                  ? "bg-zinc-800 border-zinc-700 text-white"
                  : "bg-stone-50 border-stone-200 text-black"
              }`}
            />
          </div>

          <div>
            <Label htmlFor="category" className={`text-base mb-2 block ${
              theme === "dark" ? "text-zinc-300" : "text-stone-700"
            }`}>
              Category
            </Label>
            <Select value={formData.category} onValueChange={(value) => setFormData({ ...formData, category: value })}>
              <SelectTrigger className={`h-12 rounded-xl ${
                theme === "dark"
                  ? "bg-zinc-800 border-zinc-700 text-white"
                  : "bg-stone-50 border-stone-200 text-black"
              }`}>
                <SelectValue placeholder="Select category" />
              </SelectTrigger>
              <SelectContent>
                {categories.map((category) => (
                  <SelectItem key={category} value={category}>
                    {category.charAt(0).toUpperCase() + category.slice(1)}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div>
            <Label htmlFor="image-url" className={`text-base mb-2 block ${
              theme === "dark" ? "text-zinc-300" : "text-stone-700"
            }`}>
              Image URL
            </Label>
            <Input
              id="image-url"
              value={formData.image_url}
              onChange={(e) => setFormData({ ...formData, image_url: e.target.value })}
              placeholder="https://example.com/image.jpg"
              className={`h-12 rounded-xl ${
                theme === "dark"
                  ? "bg-zinc-800 border-zinc-700 text-white"
                  : "bg-stone-50 border-stone-200 text-black"
              }`}
            />
          </div>

          <div className="flex gap-3">
            <Button
              type="button"
              onClick={onClose}
              variant="outline"
              className="flex-1 h-12 rounded-xl"
            >
              Cancel
            </Button>
            <Button
              type="submit"
              disabled={!formData.name || !formData.category || !formData.image_url || uploading}
              className={`flex-1 h-12 rounded-xl ${
                theme === "dark"
                  ? "bg-white text-black hover:bg-zinc-100"
                  : "bg-black text-white hover:bg-stone-900"
              }`}
            >
              {uploading ? "Uploading..." : "Upload Item"}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
}

// src/components/cabinet/UploadItemModal.vue
<template>
  <div
    v-if="open"
    class="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4"
    @click="$emit('close')"
  >
    <div
      :class="`w-full max-w-md rounded-xl p-6 ${
        theme === 'dark' ? 'bg-zinc-900' : 'bg-white'
      }`"
      @click.stop
    >
      <h2 :class="`text-xl font-bold mb-4 ${
        theme === 'dark' ? 'text-white' : 'text-black'
      }`">
        Add New Item
      </h2>
      
      <form @submit.prevent="handleSubmit">
        <div class="space-y-4">
          <div>
            <label :class="`block text-sm font-medium mb-2 ${
              theme === 'dark' ? 'text-zinc-300' : 'text-stone-700'
            }`">
              Item Name
            </label>
            <input
              v-model="formData.name"
              type="text"
              required
              :class="`w-full px-3 py-2 rounded-lg border ${
                theme === 'dark'
                  ? 'bg-zinc-800 border-zinc-700 text-white'
                  : 'bg-white border-stone-300 text-black'
              }`"
              placeholder="Enter item name"
            />
          </div>
          
          <div>
            <label :class="`block text-sm font-medium mb-2 ${
              theme === 'dark' ? 'text-zinc-300' : 'text-stone-700'
            }`">
              Category
            </label>
            <select
              v-model="formData.category"
              required
              :class="`w-full px-3 py-2 rounded-lg border ${
                theme === 'dark'
                  ? 'bg-zinc-800 border-zinc-700 text-white'
                  : 'bg-white border-stone-300 text-black'
              }`"
            >
              <option value="">Select category</option>
              <option
                v-for="category in categories"
                :key="category"
                :value="category"
              >
                {{ category }}
              </option>
            </select>
          </div>
          
          <div>
            <label :class="`block text-sm font-medium mb-2 ${
              theme === 'dark' ? 'text-zinc-300' : 'text-stone-700'
            }`">
              Brand
            </label>
            <input
              v-model="formData.brand"
              type="text"
              :class="`w-full px-3 py-2 rounded-lg border ${
                theme === 'dark'
                  ? 'bg-zinc-800 border-zinc-700 text-white'
                  : 'bg-white border-stone-300 text-black'
              }`"
              placeholder="Enter brand (optional)"
            />
          </div>
          
          <div>
            <label :class="`block text-sm font-medium mb-2 ${
              theme === 'dark' ? 'text-zinc-300' : 'text-stone-700'
            }`">
              Image
            </label>
            <input
              ref="fileInput"
              type="file"
              accept="image/*"
              @change="handleFileSelect"
              :class="`w-full px-3 py-2 rounded-lg border ${
                theme === 'dark'
                  ? 'bg-zinc-800 border-zinc-700 text-white'
                  : 'bg-white border-stone-300 text-black'
              }`"
            />
          </div>
        </div>
        
        <div class="flex gap-3 mt-6">
          <button
            type="button"
            @click="$emit('close')"
            :class="`flex-1 px-4 py-2 rounded-lg font-medium transition-all duration-200 ${
              theme === 'dark'
                ? 'bg-zinc-800 text-zinc-300 hover:bg-zinc-700'
                : 'bg-stone-100 text-stone-700 hover:bg-stone-200'
            }`"
          >
            Cancel
          </button>
          <button
            type="submit"
            :disabled="uploading"
            :class="`flex-1 px-4 py-2 rounded-lg font-medium transition-all duration-200 ${
              theme === 'dark'
                ? 'bg-white text-black hover:bg-zinc-200'
                : 'bg-black text-white hover:bg-zinc-800'
            } ${uploading ? 'opacity-50 cursor-not-allowed' : ''}`"
          >
            {{ uploading ? 'Adding...' : 'Add Item' }}
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useTheme } from '@/composables/useTheme'
import { api } from '@/api/client'

const { theme } = useTheme()

const props = defineProps({
  open: {
    type: Boolean,
    default: false
  }
})

const emit = defineEmits(['close', 'itemAdded'])

const formData = ref({
  name: '',
  category: '',
  brand: '',
  image_url: ''
})

const uploading = ref(false)
const fileInput = ref(null)

const categories = [
  'tops',
  'bottoms', 
  'shoes',
  'accessories',
  'outerwear'
]

const handleFileSelect = (event) => {
  const file = event.target.files[0]
  if (file) {
    const reader = new FileReader()
    reader.onload = (e) => {
      formData.value.image_url = e.target.result
    }
    reader.readAsDataURL(file)
  }
}

const handleSubmit = async () => {
  if (!formData.value.name || !formData.value.category) return

  uploading.value = true
  try {
    const itemData = {
      ...formData.value,
      created_by: 'demo@stylesnap.com', // This would come from auth context
      is_favorite: false
    }
    
    await api.entities.ClothingItem.create(itemData)
    
    // Reset form
    formData.value = {
      name: '',
      category: '',
      brand: '',
      image_url: ''
    }
    
    emit('itemAdded')
    emit('close')
  } catch (error) {
    console.error('Error uploading item:', error)
  } finally {
    uploading.value = false
  }
}
</script>
